AWSTemplateFormatVersion: '2010-09-09'
Description: 'OnboardAI - Insurance Onboarding Platform Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, production]
  
  DocumentsBucketName:
    Type: String
    Default: onboard-ai-documents

Resources:
  # ============================================
  # DynamoDB Tables
  # ============================================
  
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'applications-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: applicationId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: applicationId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AIResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ai-results-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: resultId
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: resultId
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment

  KYCResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kyc-results-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: applicationId
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: applicationId
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment

  PolicyRecommendationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'policy-recommendations-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: recommendationId
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: recommendationId
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ComplianceFlagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'compliance-flags-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: flagId
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: flagId
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AuditLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'audit-logs-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # S3 Buckets
  # ============================================

  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DocumentsBucketName}-${AWS::AccountId}-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldDocuments
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 2555  # 7 years
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # IAM Roles and Policies
  # ============================================

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'OnboardAI-Lambda-Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !GetAtt ApplicationsTable.Arn
                  - !GetAtt AIResultsTable.Arn
                  - !GetAtt KYCResultsTable.Arn
                  - !GetAtt PolicyRecommendationsTable.Arn
                  - !GetAtt ComplianceFlagsTable.Arn
                  - !GetAtt AuditLogsTable.Arn
                  - !Sub '${UsersTable.Arn}/index/*'
                  - !Sub '${ApplicationsTable.Arn}/index/*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${DocumentsBucket.Arn}/*'
        - PolicyName: TextractAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - textract:AnalyzeDocument
                  - textract:GetDocumentAnalysis
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  # ============================================
  # Lambda Functions
  # ============================================

  SubmitUserInfoFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'onboard-ai-submit-user-info-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          AUDIT_TABLE: !Ref AuditLogsTable
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          // Placeholder - replace with actual code
          exports.handler = async (event) => {
            return { statusCode: 200, body: JSON.stringify({ message: 'Function deployed' }) };
          };

  ProcessDocumentsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'onboard-ai-process-documents-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          APPLICATIONS_TABLE: !Ref ApplicationsTable
          AI_RESULTS_TABLE: !Ref AIResultsTable
          USERS_TABLE: !Ref UsersTable
          DOCUMENTS_BUCKET: !Ref DocumentsBucket
          AUDIT_TABLE: !Ref AuditLogsTable
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return { statusCode: 200, body: JSON.stringify({ message: 'Function deployed' }) };
          };

  PerformKYCFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'onboard-ai-perform-kyc-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          KYC_RESULTS_TABLE: !Ref KYCResultsTable
          COMPLIANCE_TABLE: !Ref ComplianceFlagsTable
          AUDIT_TABLE: !Ref AuditLogsTable
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return { statusCode: 200, body: JSON.stringify({ message: 'Function deployed' }) };
          };

  GeneratePolicyRecommendationsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'onboard-ai-generate-recommendations-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          RECOMMENDATIONS_TABLE: !Ref PolicyRecommendationsTable
          AUDIT_TABLE: !Ref AuditLogsTable
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return { statusCode: 200, body: JSON.stringify({ message: 'Function deployed' }) };
          };

  # ============================================
  # API Gateway
  # ============================================

  OnboardAIAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'OnboardAI-API-${Environment}'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowHeaders:
          - '*'

  APIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref OnboardAIAPI
      StageName: !Ref Environment
      AutoDeploy: true
      LogSettings:
        DestinationArn: !GetAtt APILogGroup.Arn
        Format: '$context.requestId $context.error.message $context.error.messageString'

  APILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/OnboardAI-${Environment}'
      RetentionInDays: 30

  # ============================================
  # CloudWatch Alarms
  # ============================================

  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'OnboardAI-High-Error-Rate-${Environment}'
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold

Outputs:
  APIEndpoint:
    Description: API Gateway Endpoint
    Value: !Sub 'https://${OnboardAIAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'

  DocumentsBucketName:
    Description: S3 Bucket for Documents
    Value: !Ref DocumentsBucket

  UsersTableName:
    Description: DynamoDB Users Table
    Value: !Ref UsersTable

  ApplicationsTableName:
    Description: DynamoDB Applications Table
    Value: !Ref ApplicationsTable
